export default function ReportFooter({ summary = {} }) {
  return (
    <footer className="mt-8 border-t border-white/10 pt-5 text-center text-xs uppercase tracking-[0.16em] text-slate-400">
      {summary.scan_id || 'scan-000'} • Generated by VulnScan • Confidential security assessment
    </footer>
  );
}
